import type { GameServerView } from "@/features/servers/lib/types";

const fresh = {
  checkedAt: "2026-08-14T20:00:00.000Z",
  lastSuccessfulAt: "2026-08-14T20:00:00.000Z",
  freshUntil: "2026-08-15T20:00:00.000Z",
  isStale: false,
  source: "manual",
};

export const MOCK_SERVERS: GameServerView[] = [
  {
    publicRef: "KOBA-SRV-RUST0001",
    slug: "legacy-raiders-us",
    name: "Legacy Raiders US",
    description: "Weekly wipe community Rust server.",
    game: "Rust",
    gameSlug: "rust",
    platformFamily: "PC",
    region: "US-East",
    country: "US",
    tags: ["modded", "weekly-wipe"],
    ownerHandle: "ironwright",
    ownerAccountType: "BUSINESS",
    linkedShopSlug: "ironwright-trading-co",
    joinInfo: "connect legacy.example:28015",
    displayHost: "legacy.example",
    verificationStatus: "VERIFIED",
    publicationStatus: "PUBLISHED",
    favouriteCount: 12,
    favouritedByMe: false,
    capabilities: [
      "STATUS",
      "PLAYER_COUNT",
      "QUEUE_COUNT",
      "MAP_INFO",
      "MAP_SIZE",
      "PC",
      "JOIN_LINK",
    ],
    freshness: { ...fresh, source: "manual" },
    status: "ONLINE",
    statusState: "AVAILABLE",
    livePlayers: 142,
    maxPlayers: 200,
    playersState: "AVAILABLE",
    queue: 12,
    queueState: "AVAILABLE",
    mapName: "Procedural",
    mapSize: "4250",
    mapState: "AVAILABLE",
    pingState: "NOT_SUPPORTED",
    activeMapRarity: null,
    activeMapTitle: null,
  },
  {
    publicRef: "KOBA-SRV-MC0001",
    slug: "blockforge-survival",
    name: "Blockforge Survival",
    description: null,
    game: "Minecraft Java",
    gameSlug: "minecraft-java",
    platformFamily: "PC",
    region: "EU-West",
    country: "DE",
    tags: ["survival", "whitelist"],
    ownerHandle: "raidmaps",
    ownerAccountType: "INFLUENCER",
    linkedShopSlug: null,
    joinInfo: "play.blockforge.example",
    displayHost: "play.blockforge.example",
    verificationStatus: "VERIFIED",
    publicationStatus: "PUBLISHED",
    favouriteCount: 4,
    favouritedByMe: false,
    capabilities: ["STATUS", "PLAYER_COUNT", "PING", "PUBLIC_QUERY", "MAP_INFO", "PC", "JOIN_LINK"],
    freshness: { ...fresh, source: "minecraft-java", checkedAt: "2026-08-14T19:55:00.000Z" },
    status: "ONLINE",
    statusState: "AVAILABLE",
    livePlayers: 48,
    maxPlayers: 100,
    playersState: "AVAILABLE",
    queueState: "NOT_SUPPORTED",
    mapName: "A Minecraft Server",
    mapState: "AVAILABLE",
    pingMs: 42,
    pingState: "AVAILABLE",
    activeMapRarity: null,
    activeMapTitle: null,
  },
  {
    publicRef: "KOBA-SRV-CON0001",
    slug: "console-dayz-eu",
    name: "Console DayZ EU",
    description: null,
    game: "DayZ",
    gameSlug: "dayz",
    platformFamily: "CONSOLE",
    region: "EU",
    country: null,
    tags: ["official-style"],
    ownerHandle: "maxbuilds",
    ownerAccountType: "BUSINESS",
    linkedShopSlug: null,
    joinInfo: null,
    displayHost: null,
    verificationStatus: "VERIFIED",
    publicationStatus: "PUBLISHED",
    favouriteCount: 0,
    favouritedByMe: false,
    capabilities: ["CONSOLE", "STATUS", "JOIN_LINK"],
    freshness: {
      checkedAt: null,
      lastSuccessfulAt: null,
      freshUntil: null,
      isStale: true,
      source: "manual",
    },
    status: "UNKNOWN",
    statusState: "UNKNOWN",
    playersState: "NOT_SUPPORTED",
    queueState: "NOT_SUPPORTED",
    mapState: "NOT_SUPPORTED",
    pingState: "NOT_SUPPORTED",
    activeMapRarity: null,
    activeMapTitle: null,
  },
];

export function getMockServer(slug: string): GameServerView | undefined {
  return MOCK_SERVERS.find((server) => server.slug === slug);
}
