packages:
  - "."

allowBuilds:
  '@prisma/engines': false
  '@sentry/cli': false
  esbuild: false
  prisma: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@hookform/resolvers@5.8.0'
