-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'PLUGIN_API_KEY_ROTATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_SUBSCRIPTION_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_SUBSCRIPTION_CANCELED';
ALTER TYPE "AuditAction" ADD VALUE 'PRODUCT_SUBSCRIPTION_EXPIRED';
