import type { AidenAssetView, AidenJobView } from "@/features/aiden/lib/types";

export const MOCK_AIDEN_JOBS: AidenJobView[] = [
  {
    publicRef: "KOBA-ADN-JOB0001",
    prompt: "Weathered metal crate skin for Rust monuments, desaturated greens",
    game: "Rust",
    platform: "STEAM",
    assetType: "SKIN",
    state: "COMPLETED",
    coinCostPreview: 40,
    estimatedCostCoins: "40",
    actualCostCoins: "40",
    coinCostActual: 38,
    provider: "mock",
    model: "aiden-mock-concept",
    modelVersion: "1",
    readiness: "REQUIRES_CONVERSION",
    failureReason: null,
    createdAt: "2026-08-14T10:00:00.000Z",
    assetPublicRef: "KOBA-ADN-AST0001",
  },
  {
    publicRef: "KOBA-ADN-JOB0002",
    prompt: "Procedural canyon terrain blockout",
    game: "ARK: SA",
    platform: "STEAM",
    assetType: "TERRAIN",
    state: "PROCESSING",
    coinCostPreview: 120,
    estimatedCostCoins: "120",
    actualCostCoins: null,
    coinCostActual: null,
    provider: "mock",
    model: "aiden-mock-concept",
    modelVersion: "1",
    readiness: "CONCEPT_ONLY",
    failureReason: null,
    createdAt: "2026-08-14T19:00:00.000Z",
    assetPublicRef: null,
  },
  {
    publicRef: "KOBA-ADN-JOB0003",
    prompt: "Neon nameplate concept",
    game: "KOBA",
    platform: "STEAM",
    assetType: "CONCEPT_IMAGE",
    state: "FAILED",
    coinCostPreview: 15,
    estimatedCostCoins: "15",
    actualCostCoins: null,
    coinCostActual: null,
    provider: "mock",
    model: "aiden-mock-concept",
    modelVersion: "1",
    readiness: "CONCEPT_ONLY",
    failureReason: "Provider not connected",
    createdAt: "2026-08-13T16:00:00.000Z",
    assetPublicRef: null,
  },
];

export const MOCK_AIDEN_LIBRARY: AidenAssetView[] = [
  {
    publicRef: "KOBA-ADN-AST0001",
    title: "Oxide crate skin draft",
    assetType: "SKIN",
    technicalStatus: "REQUIRES_CONVERSION",
    moderation: "PRIVATE",
    game: "Rust",
    previewLabel: "Preview still",
    provider: "mock",
    model: "aiden-mock-concept",
    assetUrl: null,
    publishedProductSlug: null,
  },
  {
    publicRef: "KOBA-ADN-AST0002",
    title: "Canyon blockout",
    assetType: "TERRAIN",
    technicalStatus: "CONCEPT_ONLY",
    moderation: "PRIVATE",
    game: "ARK: SA",
    previewLabel: "Concept board",
    provider: "mock",
    model: "aiden-mock-concept",
    assetUrl: null,
    publishedProductSlug: null,
  },
  {
    publicRef: "KOBA-ADN-AST0003",
    title: "Raid prop kit",
    assetType: "PROP",
    technicalStatus: "GAME_READY",
    moderation: "PENDING_REVIEW",
    game: "Rust",
    previewLabel: "FBX preview",
    provider: "mock",
    model: "aiden-mock-concept",
    assetUrl: null,
    publishedProductSlug: null,
  },
];
